Add cNFT support to Explorer
solana-labs/explorer pull request #338
Opened 2024-05-14 04:57 UTC by ngundotra

- [x] account header
- [x] account data
- [x] generic cache
- [ ] cnft tabs (metadata, attributes)

2024-05-24 19:40 UTC, jnwng requested changes

2024-05-24 19:40 UTC, jnwng commented on app/components/account/CompressedNftCard.tsx
> +                    <td className="text-lg-end">{`${compressedNft.royalty.basis_points / 100}%`}</td>
round this to two decimal points or you get weird overflows

2024-05-24 19:40 UTC, jnwng commented on app/components/account/CompressedNftCard.tsx
> +    );
this code smells, there's really no other dropdown code?

2024-05-24 19:40 UTC, jnwng commented on app/components/account/CompressedNftCard.tsx
> +        'This NFT does not have on-chain data, but can be transferred and traded on-chain normally. This tag guarantees that this compressed NFT has the correct format.';
this is slightly confusing, here's a suggestion:
```
This NFT does not have a corresponding account, but uses verified ledger data to allow for transfers and trades. The existence of this tag ensures that the compressed NFT is verifiably up-to-date with the chain.
```

2024-05-24 19:40 UTC, jnwng commented on app/providers/compressed-nft.tsx
> +        return fetch(`${url}`, {
neither here nor there but https://www.npmjs.com/package/@tanstack/react-query or [useSWR](https://blog.logrocket.com/handling-data-fetching-next-js-useswr/) might be better abstractions for caching these API calls

2024-05-24 19:40 UTC, jnwng commented on app/providers/compressed-nft.tsx
> +    interface: string;
any chance we can pull this from one of the types declarations, perhaps from https://www.npmjs.com/package/@metaplex-foundation/digital-asset-standard-api

2024-05-27 15:21 UTC, mcintyre94 commented on app/providers/compressed-nft.tsx
> +        return fetch(`${url}`, {
We do use SWR in some other places FWIW

2024-05-29 16:03 UTC, ngundotra commented on app/components/account/CompressedNftCard.tsx
> +    );
reusing existing dropdown code for normal creators dropdown for metadata

2024-05-29 16:04 UTC, ngundotra commented on app/providers/compressed-nft.tsx
> +    interface: string;
Adding modern deps is PITA. Worth doing if we also upgrade anchor (using `project-serum/anchor` still)

2024-05-29 16:42 UTC, ngundotra commented on app/components/account/CompressedNftCard.tsx
> +                    <td className="text-lg-end">{`${compressedNft.royalty.basis_points / 100}%`}</td>
Should be alright bc `basis_points` never has decimals

2024-05-29 16:42 UTC, ngundotra commented on app/components/account/CompressedNftCard.tsx
> +        'This NFT does not have on-chain data, but can be transferred and traded on-chain normally. This tag guarantees that this compressed NFT has the correct format.';
Adding

2024-05-29 16:46 UTC, merged